services:

  api:
    build:
      context: ./api

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - api
    
