worker_processes auto;

events { worker_connections 1024; }

http {
  
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

  # Cache
  proxy_cache_path  /var/cache/nginx
                    levels=1:2
                    keys_zone=api_cache:10m
                    max_size=100m
                    inactive=60m
                    use_temp_path=off;

  merge_slashes on;

  # Compressão gzip
  gzip on;
  gzip_types application/json text/plain;
  gzip_vary on;
  gzip_min_length 1000;
  gzip_proxied any;

  # Logs
  log_format structured_text  '[$time_iso8601] $remote_addr '
                              '"$request_method $request_uri" $status '
                              'upstream_response_time=$upstream_response_time';

  server {
    listen 80;

    # Health check do nginx
    location /health {
      add_header Content-Type application/json;
      return 200 '{"status": "ok", "component": "nginx"}';
    }

    # Proxy para api/swagger
    location ~ ^/api/(swagger|swagger-ui|v3/api-docs|swagger-ui.html) {
      # Basic auth
      auth_basic "Área Restrita - Swagger";
      auth_basic_user_file /etc/nginx/.htpasswd;

      # Proxy
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://api:8080;

      # Headers de segurança
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;

      # Logs
      access_log /var/log/nginx/swagger_access.log structured_text;
      error_log /var/log/nginx/swagger_error.log;

      # Remove trailing slash para evitar problemas de roteamento
      rewrite ^(.+)/$ $1 break;
    }

    # Proxy para API
    location /api/ {
      # Proxy
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://api:8080;

      # Cache
      proxy_cache api_cache;
      proxy_cache_methods GET;
      proxy_cache_valid 200 10s;
      proxy_no_cache $http_authorization $http_cookie;
      proxy_cache_bypass $http_authorization $http_cookie;

      # Headers de cache
      add_header X-Cache-Status $upstream_cache_status;
      add_header X-Cache-TTL "10s";
      
      # Headers de segurança
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;

      # Header de rate limit
      add_header X-Ratelimit-Rule "5r/s burst=10" always;

      # Logs
      access_log /var/log/nginx/api_access.log structured_text;
      error_log /var/log/nginx/api_error.log;

      # Limite de payload
      client_max_body_size 1m;

      # Remove trailing slash para evitar problemas de roteamento
      rewrite ^(.+)/$ $1 break;

      # Rate limiting
      limit_req zone=api_limit burst=10 nodelay;
      limit_req_status 429;
    }
  }
}