worker_processes auto;

events { worker_connections 1024; }

http {
  
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

  merge_slashes on;

  # Compressão gzip
  gzip on;
  gzip_types application/json text/plain;
  gzip_vary on;
  gzip_min_length 1000;
  gzip_proxied any;

  # Logs
  log_format structured_text  '[$time_iso8601] $remote_addr '
                              '"$request_method $request_uri" $status '
                              'upstream_response_time=$upstream_response_time';

  server {
    listen 80;

    location /health {
      add_header Content-Type application/json;
      return 200 '{"status": "ok", "component": "nginx"}';
    }

    location /api/ {
      # Proxy
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://api:8080;
      
      # Headers de segurança
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;

      # Header de rate limit
      add_header X-Ratelimit-Rule "5r/s burst=10" always;

      # Logs
      access_log /var/log/nginx/api_access.log structured_text;
      error_log /var/log/nginx/api_error.log;

      # Limite de payload
      client_max_body_size 1m;

      # Remove trailing slash para evitar problemas de roteamento
      rewrite ^(.+)/$ $1 break;

      # Rate limiting
      limit_req zone=api_limit burst=10 nodelay;
      limit_req_status 429;
    }
  }
}